# Generated by Django 4.2.4 on 2023-10-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='movieType',
            field=models.CharField(default='action', max_length=100),
        ),
    ]
